/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('invoice_contacts', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');

        table.string('contact_type', 50).notNullable(); // e.g., 'billing', 'shipping'
        table.integer('invoice_id').unsigned().notNullable().references('id').inTable('invoices').onDelete('CASCADE');

        // Contact Info
        table.string('email');
        table.string('phone_number');
        table.string('website');

        // Address
        table.string('address_line1');
        table.integer('city_id').references('id').inTable('city');
        table.integer('state_id').references('id').inTable('state');
        table.integer('pincode');
        table.string('country').defaultTo('India');

        // Audit Fields
        table.integer('created_by').references('id').inTable('users');
        table.integer('updated_by').references('id').inTable('users');
        table.timestamps(true, true);
        table.boolean('is_active').notNullable().defaultTo(true);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists('invoice_contacts');
};
