/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('invoice_challans', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer('invoice_id').nullable().references('id').inTable('invoices').onDelete('SET NULL');

        table.string('challan_no', 50).notNullable();
        table.date('challan_date').notNullable();
        table.string('customer_name', 255).notNullable();
        table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms');
        table.boolean('is_invoiced').defaultTo(false);

        table.integer('created_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.integer('updated_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.timestamps(true, true); // adds created_at and updated_at
        table.boolean('is_active').notNullable().defaultTo(true);

        table.unique(['firm_id', 'challan_no'], {
            indexName: 'unique_firm_challan_no'
        });

        table.unique(['id', 'invoice_id'], {
            indexName: 'unique_id_invoice'
        });
    });
};


/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists('invoice_challans');
};
