/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('eway_bills', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer('invoice_id').nullable().references('id').inTable('invoices').onDelete('SET NULL');
        table.string('customer_name', 255).notNullable(); // Customer name
        table.string('eway_bill_no', 50).notNullable().unique();
        table.date('eway_bill_date').notNullable();
        table.date('valid_upto').nullable();

        table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms');
        table.boolean('is_invoiced').defaultTo(false);

        table.integer('created_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.integer('updated_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.timestamps(true, true); // adds created_at and updated_at
        table.boolean('is_active').notNullable().defaultTo(true);
    });
};


/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists('eway_bills');
};
