/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. Create ENUM type
    await knex.raw(`
    CREATE TYPE entity_type_enum AS ENUM ('firm', 'client', 'user', 'vendor', 'employee');
  `);

    // 2. Create table using the ENUM
    await knex.schema.createTable('user_contacts', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');

        // Use ENUM
        table
            .specificType('entity_type', 'entity_type_enum')
            .notNullable();

        table.integer('entity_id').unsigned().notNullable();

        // Contact Info
        table.string('email');
        table.string('phone_number');
        table.string('website');

        // Address
        table.string('address_line1');
        table.integer('city_id').references('id').inTable('city');
        table.integer('state_id').references('id').inTable('state');
        table.integer('pincode');
        table.string('country').defaultTo('India');

        // Audit Fields
        table.integer('created_by').references('id').inTable('users');
        table.integer('updated_by').references('id').inTable('users');
        table.timestamps(true, true);
        table.boolean('is_active').notNullable().defaultTo(true);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('user_contacts');
    
    // Then drop the ENUM type
    await knex.raw(`DROP TYPE IF EXISTS entity_type_enum`);
};
