/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('gst_slabs', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.text('description').notNullable(); // Optional: '18% GST on general goods'
        table.decimal('gst_rate', 5, 2).notNullable();
        table.decimal('cgst_rate', 5, 2).notNullable();
        table.decimal('sgst_rate', 5, 2).notNullable();
        table.decimal('igst_rate', 5, 2).notNullable();
        table.decimal('cess_rate', 5, 2).defaultTo(0.00);
        table.boolean('is_service').notNullable();
        table.date('effective_from').notNullable();
        table.date('effective_to').defaultTo(null);
        table.integer('created_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.integer('updated_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.timestamps(true, true); // adds created_at and updated_at
        table.boolean('is_active').notNullable().defaultTo(true);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists('gst_slabs');
};
