/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
        await knex.raw(`
        CREATE TYPE firm_type_enum AS ENUM (
        'Proprietorship',
        'Partnership',
        'LLP',
        'Pvt Ltd',
        'Public Ltd',
        'One Person Company',
        'Trust',
        'Society',
        'Government Entity',
        'Foreign Company',
        'Personal',
        'Other'
        );
    `);

    return knex.schema.createTable('firms', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.string('firm_name').notNullable();
        table.string('trade_name');
        // table.string('firm_type'); // e.g., Proprietorship, Pvt Ltd, etc.
        table.specificType('firm_type', 'firm_type_enum').notNullable();
        table.string('business_activity');
        table.string('logo_url');

        // Tax info
        table.string('gstin');
        table.string('pan_number');
        table.string('cin_number');
        table.string('tan_number');

        // Invoice Preferences
        table.string('invoice_prefix').defaultTo('INV');
        table.string('invoice_start_number', 10).defaultTo('1');
        table.text('notes_footer');

        // Audit fields
        table.integer('created_by').references('id').inTable('users');
        table.integer('updated_by').references('id').inTable('users');
        table.timestamps(true, true); // created_at & updated_at
        table.boolean('is_active').notNullable().defaultTo(true);

    })
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('firms');
    await knex.raw(`DROP TYPE IF EXISTS firm_type_enum`);
};
