/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('firm_bank_accounts', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');

        table.integer('firm_id')
            .unsigned()
            .notNullable()
            .references('id')
            .inTable('firms')
            .onDelete('CASCADE');

        table.string('upi_id');
        table.string('account_holder_name').notNullable();
        table.string('account_number').notNullable();
        table.string('ifsc_code', 20).notNullable();
        table.string('bank_name').notNullable();
        table.string('branch_name').nullable();
        table.string('account_type', 50).nullable(); // e.g. 'current', 'savings'

        table.integer('created_by').references('id').inTable('users');
        table.integer('updated_by').references('id').inTable('users');
        table.timestamps(true, true); // adds created_at and updated_at
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists('firm_bank_accounts');
};
