exports.up = async function (knex) {
    await knex.schema.createTable('refresh_tokens', function (table) {
        // Identity column for PostgreSQL
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');

        table.integer('user_id').unsigned().notNullable()
            .references('id').inTable('users').onDelete('CASCADE');

        table.text('token_hash').notNullable();
        table.timestamp('created_at').defaultTo(knex.fn.now());
        table.timestamp('updated_at').defaultTo(knex.fn.now());
        table.timestamp('expires_at').notNullable();
        table.timestamp('revoked_at').nullable();
        table.integer('replaced_by_token_id').unsigned();
        table.string('ip_address', 45);
        table.text('user_agent');
        table.uuid('device_id');
        table.boolean('is_active').notNullable().defaultTo(true);

        table.integer('created_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.integer('updated_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
    });
};

exports.down = async function (knex) {
    await knex.schema.dropTable('refresh_tokens');
};
