exports.up = async function (knex) {
    await knex.schema.raw(`
        CREATE TABLE user_roles (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL UNIQUE,
            slug VARCHAR(100) NOT NULL UNIQUE,
            description TEXT,
            is_active BOOLEAN DEFAULT TRUE,
            created_at TIMESTAMP DEFAULT now(),
            updated_at TIMESTAMP DEFAULT now(),
            created_by INTEGER,
            updated_by INTEGER
        );
    `);
};

exports.down = function (knex) {
    return knex.schema.dropTable('user_roles');
};
