/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function(knex) {
    return knex.schema.createTable('casbin_abac_policy', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.string('sub').notNullable(); // subject
        table.text('obj').notNullable();  // object
        table.string('act').notNullable();     // action (e.g., get, post)
        table.boolean('is_active').defaultTo(true);
        table.jsonb('conditions').defaultTo(knex.raw(`'true'::jsonb`)).nullable();
    
        // Audit fields
        table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
        table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
        table.integer('created_by').nullable();
        table.integer('updated_by').nullable();
      });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function(knex) {
    return knex.schema.dropTableIfExists('casbin_abac_policy');
};
