/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('purchase_orders', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer('invoice_id').nullable().references('id').inTable('invoices').onDelete('SET NULL');
        table.string('po_no', 50).notNullable();
        table.date('po_date').notNullable();
        table.string('customer_name', 255).notNullable();
        table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms');
        table.boolean('is_invoiced').defaultTo(false);

        table.integer('created_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.integer('updated_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.timestamps(true, true); // adds created_at and updated_at
        table.boolean('is_active').notNullable().defaultTo(true);

        table.unique(['firm_id', 'po_no']);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists('purchase_orders');
};
