/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('invoices', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');

        table.string('invoice_no').notNullable();
        table.date('invoice_date').notNullable();

        // Due Date
        table.integer('due_days').unsigned()
        table.date('due_date');

        // Firm ID
        table.integer('firm_id').unsigned().notNullable()
            .references('id').inTable('firms').onDelete('CASCADE');

        // Customer fields
        table.string('customer_name', 255).notNullable();         // Customer name
        table.boolean('has_gst').notNullable().defaultTo(false);  // Has GST number
        table.string('gst_number', 20).nullable();                // GST number

        // Invoice address
        table.integer('billing_address_id')
        table.integer('shipping_address_id')

        // Challan
        table.boolean('has_challan').notNullable().defaultTo(false);

        // Purchase Order
        table.boolean('has_po').notNullable().defaultTo(false);

        // E-way Bill
        table.boolean('has_eway_bill').notNullable().defaultTo(false);

        // Financials
        table.decimal('sub_total', 12, 2).notNullable().defaultTo(0);
        table.decimal('discount_percent', 5, 2).defaultTo(0); // per-item %
        table.decimal('discount_amount', 12, 2).defaultTo(0); // amount of discount applied to the invoice
        table.decimal('taxable_amount', 12, 2).defaultTo(0);
        table.decimal('cgst', 12, 2).defaultTo(0);
        table.decimal('sgst', 12, 2).defaultTo(0);
        table.decimal('igst', 12, 2).defaultTo(0);
        table.decimal('total', 12, 2).notNullable().defaultTo(0);
        table.decimal('round_off', 12, 2).defaultTo(0);
        table.decimal('other', 12, 2).defaultTo(0);

        // Payment Status & Mode
        table.integer('payment_status_id').unsigned().notNullable().defaultTo(1)
            .references('id').inTable('payment_statuses').onDelete('RESTRICT');
        table.integer('payment_mode_id').unsigned().notNullable().defaultTo(0)
            .references('id').inTable('payment_modes').onDelete('RESTRICT');

        table.string('status', 255).notNullable();         // Draft, Final, Cancelled

        // Audit
        table.integer('created_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.integer('updated_by').unsigned().references('id').inTable('users').onDelete('SET NULL');

        table.timestamps(true, true); // created_at and updated_at
        table.boolean('is_active').notNullable().defaultTo(true);

        // Unique invoice per firm
        table.unique(['invoice_no', 'firm_id']);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists('invoices');
};
