/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    await knex.schema.createTable('roles', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.string('name', 100).notNullable().unique();
        table.string('slug', 100).notNullable().unique();
        table.text('description');
        table.boolean('is_active').defaultTo(true);
        table.timestamp('created_at').defaultTo(knex.fn.now());
        table.timestamp('updated_at').defaultTo(knex.fn.now());
        table.integer('created_by');
        table.integer('updated_by');
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    // Drop foreign keys in other tables first if needed
    // await knex.schema.alterTable('users', function (table) {
    //     table.dropForeign('user_role_id'); // adjust FK name if necessary
    // });

    await knex.schema.dropTableIfExists('roles');
};
