/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function(knex) {
    return knex.schema.createTable('casbin_abac_policy', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.text('sub_rule').notNullable();  // subject rule (e.g., JSON or string condition)
        table.text('obj_rule').notNullable();  // object rule (e.g., path or resource condition)
        table.string('act').notNullable();     // action (e.g., get, post)
        table.boolean('is_active').defaultTo(true);
    
        // Audit fields
        table.timestamp('created_at').defaultTo(knex.fn.now());
        table.timestamp('updated_at').defaultTo(knex.fn.now());
        table.integer('created_by').nullable();
        table.integer('updated_by').nullable();
      });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function(knex) {
    return knex.schema.dropTableIfExists('casbin_abac_policy');
};
