/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    await knex.schema.createTable('user_roles', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');

        table.integer('user_id').notNullable()
            .references('id').inTable('users')
            .onDelete('CASCADE');

        table.integer('role_id').notNullable()
            .references('id').inTable('roles')
            .onDelete('CASCADE');

        table.unique(['user_id', 'role_id']); // enforce unique pair

        // Default/common columns
        table.boolean('is_active').defaultTo(true);
        table.timestamp('created_at').defaultTo(knex.fn.now());
        table.timestamp('updated_at').defaultTo(knex.fn.now());
        table.integer('created_by');
        table.integer('updated_by');
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('user_roles');
};
