/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    await knex.schema.createTable('role_permissions', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');

        table.integer('role_id').notNullable()
            .references('id').inTable('roles')
            .onDelete('CASCADE');

        table.integer('permission_id').notNullable()
            .references('id').inTable('permissions')
            .onDelete('CASCADE');

        table.unique(['role_id', 'permission_id']); // ensure no duplicate role-permission pairs

        // Default/audit columns
        table.boolean('is_active').defaultTo(true);
        table.timestamp('created_at').defaultTo(knex.fn.now());
        table.timestamp('updated_at').defaultTo(knex.fn.now());
        table.integer('created_by');
        table.integer('updated_by');
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('role_permissions');
};
