/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('gst_units', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.string('uqc', 10).notNullable().unique();  // Unit Quantity Code (e.g., PCS, KGS)
        table.string('description', 100).notNullable();  // Full description (e.g., Pieces, Kilograms)
        table.integer('created_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.integer('updated_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.timestamps(true, true); // adds created_at and updated_at
        table.boolean('is_active').notNullable().defaultTo(true);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists('gst_units');
};
