/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable('payment_modes', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.string('code', 20).notNullable().unique(); // Internal short code: e.g., CASH, UPI
        table.string('label', 50).notNullable();         // Display name: e.g., "Cash", "Google Pay"
        table.text('description').nullable();            // Optional usage instructions
        table.integer('created_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.integer('updated_by').unsigned().references('id').inTable('users').onDelete('SET NULL');
        table.timestamps(true, true); // adds created_at and updated_at
        table.boolean('is_active').notNullable().defaultTo(true);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('payment_modes');
};
