const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. shifts table
    if (!(await knex.schema.hasTable('shifts'))) {
        await knex.schema.createTable('shifts', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.string('shift_name', 100).notNullable();
            table.string('shift_code', 20).notNullable();
            table.time('start_time').notNullable();
            table.time('end_time').notNullable();
            table.integer('break_minutes').defaultTo(60);
            table.boolean('is_default').defaultTo(false);
            addDefaultColumns(table, knex);

            table.unique(['firm_id', 'shift_code'], { indexName: 'uq_shifts_firm_shift_code' });
            table.index(['firm_id', 'is_active'], 'idx_shifts_firm_active');
        });
    }

    // 2. salary_templates table
    if (!(await knex.schema.hasTable('salary_templates'))) {
        await knex.schema.createTable('salary_templates', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.string('template_name', 150).notNullable();
            table.string('template_type', 20).defaultTo('MONTHLY'); // MONTHLY | DAILY | HOURLY
            table.text('description').nullable();
            table.boolean('is_default').defaultTo(false);
            addDefaultColumns(table, knex);

            table.unique(['firm_id', 'template_name'], { indexName: 'uq_salary_templates_firm_name' });
            table.index(['firm_id', 'is_active'], 'idx_salary_templates_firm_active');
        });
    }

    // 3. salary_template_components table
    if (!(await knex.schema.hasTable('salary_template_components'))) {
        await knex.schema.createTable('salary_template_components', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('template_id').unsigned().notNullable().references('id').inTable('salary_templates').onDelete('CASCADE');
            table.string('component_name', 100).notNullable();
            table.string('component_type', 20).notNullable(); // EARNING | DEDUCTION
            table.string('calc_type', 30).notNullable(); // FIXED | PERCENT_OF_BASIC | PERCENT_OF_GROSS
            table.decimal('value', 12, 2).notNullable().defaultTo(0);
            table.boolean('is_statutory').defaultTo(false);
            table.integer('sort_order').defaultTo(0);
            addDefaultColumns(table, knex);

            table.index(['template_id', 'is_active'], 'idx_salary_comp_template_active');
        });
    }

    // 4. employees table
    if (!(await knex.schema.hasTable('employees'))) {
        await knex.schema.createTable('employees', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.integer('branch_id').unsigned().nullable().references('id').inTable('firm_branches').onDelete('SET NULL');
            table.integer('user_id').unsigned().nullable().references('id').inTable('users').onDelete('SET NULL');

            // Identity
            table.string('emp_code', 50).notNullable();
            table.string('first_name', 100).notNullable();
            table.string('last_name', 100).nullable();
            table.string('email', 150).nullable();
            table.string('phone', 25).nullable();
            table.text('photo_url').nullable();
            table.string('photo_public_id', 150).nullable();

            // Personal
            table.date('date_of_birth').nullable();
            table.string('gender', 20).nullable(); // MALE | FEMALE | OTHER
            table.string('blood_group', 10).nullable();
            table.text('address').nullable();
            table.integer('city_id').unsigned().nullable().references('id').inTable('city').onDelete('SET NULL');
            table.integer('state_id').unsigned().nullable().references('id').inTable('state').onDelete('SET NULL');
            table.string('pincode', 15).nullable();
            table.string('emergency_contact_name', 100).nullable();
            table.string('emergency_contact_phone', 25).nullable();

            // Employment
            table.date('date_of_joining').notNullable();
            table.date('date_of_exit').nullable();
            table.string('department', 100).nullable();
            table.string('designation', 100).nullable();
            table.string('employment_type', 30).notNullable().defaultTo('PERMANENT'); // PERMANENT | DAILY_WAGE | CONTRACT | PART_TIME
            table.string('status', 30).notNullable().defaultTo('ACTIVE'); // ACTIVE | RESIGNED | TERMINATED | ABSCONDED

            // Salary Configuration
            table.string('salary_type', 20).notNullable().defaultTo('MONTHLY'); // MONTHLY | DAILY | HOURLY
            table.decimal('base_salary', 12, 2).defaultTo(0);
            table.integer('salary_template_id').unsigned().nullable().references('id').inTable('salary_templates').onDelete('SET NULL');

            // Bank & Statutory Details
            table.string('bank_name', 150).nullable();
            table.string('account_number', 50).nullable();
            table.string('ifsc_code', 30).nullable();
            table.string('pan_number', 30).nullable();
            table.string('aadhar_number', 30).nullable();
            table.string('uan_number', 30).nullable();
            table.string('esi_number', 30).nullable();

            addDefaultColumns(table, knex);

            table.unique(['firm_id', 'emp_code'], { indexName: 'uq_employees_firm_emp_code' });
            table.index(['firm_id', 'is_active'], 'idx_employees_firm_active');
            table.index(['firm_id', 'status'], 'idx_employees_firm_status');
            table.index(['firm_id', 'department'], 'idx_employees_firm_dept');
            table.index(['firm_id', 'branch_id'], 'idx_employees_firm_branch');
        });
    }

    // 5. employee_shift_assignments table
    if (!(await knex.schema.hasTable('employee_shift_assignments'))) {
        await knex.schema.createTable('employee_shift_assignments', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('employee_id').unsigned().notNullable().references('id').inTable('employees').onDelete('CASCADE');
            table.integer('shift_id').unsigned().notNullable().references('id').inTable('shifts').onDelete('CASCADE');
            table.date('effective_from').notNullable();
            table.date('effective_to').nullable();
            table.integer('assigned_by').unsigned().nullable().references('id').inTable('users').onDelete('SET NULL');
            addDefaultColumns(table, knex);

            table.index(['employee_id', 'effective_from'], 'idx_shift_assign_emp_from');
            table.index(['employee_id', 'is_active'], 'idx_shift_assign_emp_active');
        });
    }
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('employee_shift_assignments');
    await knex.schema.dropTableIfExists('employees');
    await knex.schema.dropTableIfExists('salary_template_components');
    await knex.schema.dropTableIfExists('salary_templates');
    await knex.schema.dropTableIfExists('shifts');
};
