const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    if (!(await knex.schema.hasTable('user_firm_branches'))) {
        await knex.schema.createTable('user_firm_branches', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('user_id').unsigned().notNullable().references('id').inTable('users').onDelete('CASCADE');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.integer('firm_branch_id').unsigned().nullable().references('id').inTable('firm_branches').onDelete('CASCADE');
            table.integer('role_id').unsigned().notNullable().references('id').inTable('roles').onDelete('RESTRICT');
            table.boolean('is_default').notNullable().defaultTo(false);
            addDefaultColumns(table, knex);

            // Partial unique index handling nullable firm_branch_id in PostgreSQL
            table.index(['user_id', 'firm_id', 'firm_branch_id'], 'idx_user_firm_branch_mapping');
            table.index(['user_id', 'is_active'], 'idx_user_firm_branches_user_active');
        });
    }

    // Data Backfill: Ensure existing active users have a default assignment to Firm 1 Head Office
    const firstFirm = await knex('firms').orderBy('id', 'asc').first();
    if (firstFirm) {
        const hoBranch = await knex('firm_branches')
            .where({ firm_id: firstFirm.id, is_head_office: true })
            .first();

        const defaultBranchId = hoBranch?.id || null;
        const defaultRole = await knex('roles').orderBy('id', 'asc').first();
        const fallbackRoleId = defaultRole?.id || 1;

        const users = await knex('users').where({ is_active: true }).select('id', 'role_id');
        for (const u of users) {
            const existing = await knex('user_firm_branches').where({ user_id: u.id, firm_id: firstFirm.id }).first();
            if (!existing) {
                await knex('user_firm_branches').insert({
                    user_id: u.id,
                    firm_id: firstFirm.id,
                    firm_branch_id: defaultBranchId,
                    role_id: u.role_id || fallbackRoleId,
                    is_default: true,
                    is_active: true
                });
            }
        }
    }
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('user_firm_branches');
};
