const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. Add status column to purchase_orders and drop legacy single invoice columns
    await knex.schema.alterTable('purchase_orders', function (table) {
        table.string('status', 20).notNullable().defaultTo('OPEN');
        table.dropColumn('invoice_id');
        table.dropColumn('is_invoiced');
    });

    // 2. Add check constraint for status values (OPEN, COMPLETED, CANCELLED)
    await knex.raw(`
        ALTER TABLE purchase_orders 
        ADD CONSTRAINT check_po_status 
        CHECK (status IN ('OPEN', 'COMPLETED', 'CANCELLED'))
    `);

    // 3. Create purchase_order_invoices junction table
    await knex.schema.createTable('purchase_order_invoices', function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer('purchase_order_id').unsigned().notNullable()
            .references('id').inTable('purchase_orders').onDelete('CASCADE');
        table.integer('invoice_id').unsigned().notNullable()
            .references('id').inTable('invoices').onDelete('CASCADE');
        
        addDefaultColumns(table, knex);

        table.unique(['purchase_order_id', 'invoice_id']);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    // 1. Drop mapping table
    await knex.schema.dropTableIfExists('purchase_order_invoices');

    // 2. Remove check constraint
    await knex.raw(`
        ALTER TABLE purchase_orders 
        DROP CONSTRAINT IF EXISTS check_po_status
    `);

    // 3. Revert purchase_orders table changes
    await knex.schema.alterTable('purchase_orders', function (table) {
        table.dropColumn('status');
        table.integer('invoice_id').nullable().references('id').inTable('invoices').onDelete('SET NULL');
        table.boolean('is_invoiced').defaultTo(false);
    });
};
