const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable("attachments", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("firm_id").unsigned().nullable().references("id").inTable("firms").onDelete("CASCADE");
        table.string("entity_type", 50).notNullable(); // 'PARTY', 'INVOICE', 'PURCHASE_ORDER', 'CHALLAN', 'EWAY_BILL'
        table.bigInteger("entity_id").notNullable();
        table.string("doc_type", 50).notNullable(); // 'LOGO', 'GST_CERT', 'PAN_CARD', 'MSME_CERT', 'CHEQUE', 'AGREEMENT', 'OTHER'
        table.string("title", 255).nullable();
        table.string("original_name", 255).notNullable();
        table.bigInteger("file_size_bytes").notNullable();
        table.string("mime_type", 100).notNullable();
        table.string("public_id", 255).notNullable();
        table.string("secure_url", 500).notNullable();
        table.string("resource_type", 50).defaultTo("auto");
        addDefaultColumns(table, knex);
        table.index(["entity_type", "entity_id", "is_active"], "idx_attachments_entity_lookup");
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists("attachments");
};
