const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable("party_contacts", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');

        // Party reference
        table.integer("party_id").unsigned().notNullable().references("id").inTable("parties").onDelete("CASCADE");

        // Contact role reference
        table.integer("contact_role_id").unsigned().notNullable().references("id").inTable("contact_roles").onDelete("RESTRICT");
        table.string("contact_name", 100).notNullable();
        table.string("designation", 100);
        table.string("mobile", 15);
        table.string("email", 150);
        table.boolean("is_primary").notNullable().defaultTo(false);
        addDefaultColumns(table, knex);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists("party_contacts");
};
