const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable("party_addresses", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("party_id").unsigned().notNullable().references("id").inTable("parties").onDelete("CASCADE");
        table.integer("address_type_id").unsigned().notNullable().references("id").inTable("address_types").onDelete("RESTRICT");
        table.string("address", 200).notNullable();
        table.integer('city_id').references('id').inTable('city');
        table.integer('state_id').references('id').inTable('state');
        table.string("country", 100).defaultTo("India");
        table.string("pincode", 10);
        addDefaultColumns(table, knex);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists("party_addresses");
};
