const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. Create vendor_bills table
    await knex.schema.createTable("vendor_bills", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("firm_id").unsigned().notNullable().references("id").inTable("firms").onDelete("CASCADE");
        table.integer("party_id").unsigned().notNullable().references("id").inTable("parties").onDelete("RESTRICT");
        table.integer("branch_id").unsigned().nullable().references("id").inTable("party_branches").onDelete("SET NULL");
        
        table.string("bill_no", 100).notNullable(); // Vendor's invoice number e.g. 'INV-9021'
        table.date("bill_date").notNullable();
        table.integer("due_days").unsigned().nullable();
        table.date("due_date").nullable();
        
        // Monetary & Tax Breakdown
        table.decimal("taxable_amount", 12, 2).notNullable().defaultTo(0.00);
        table.decimal("cgst", 12, 2).notNullable().defaultTo(0.00);
        table.decimal("sgst", 12, 2).notNullable().defaultTo(0.00);
        table.decimal("igst", 12, 2).notNullable().defaultTo(0.00);
        table.decimal("other_charges", 12, 2).notNullable().defaultTo(0.00);
        table.decimal("round_off", 12, 2).notNullable().defaultTo(0.00);
        table.decimal("total", 12, 2).notNullable().defaultTo(0.00);
        
        // Payment Tracking
        table.decimal("paid_amount", 12, 2).notNullable().defaultTo(0.00);
        table.decimal("balance_amount", 12, 2).notNullable().defaultTo(0.00);
        table.integer("payment_status_id").unsigned().notNullable().defaultTo(1).references("id").inTable("payment_statuses").onDelete("RESTRICT");
        
        // Status & Notes
        table.string("status", 50).notNullable().defaultTo("ACTIVE"); // 'ACTIVE', 'CANCELLED'
        table.text("notes").nullable();
        
        // Default audit columns
        addDefaultColumns(table, knex);
        
        // Constraints and indexes
        table.unique(["firm_id", "party_id", "bill_no"], "unq_vendor_bills_firm_party_bill_no");
        table.index(["firm_id", "party_id", "is_active"], "idx_vendor_bills_firm_party");
        table.index(["firm_id", "payment_status_id"], "idx_vendor_bills_firm_payment_status");
        table.index(["firm_id", "bill_date"], "idx_vendor_bills_firm_bill_date");
    });

    // 2. Alter payment_allocations to support vendor bills
    await knex.schema.alterTable("payment_allocations", function (table) {
        table.integer("invoice_id").unsigned().nullable().alter();
        table.integer("vendor_bill_id").unsigned().nullable().references("id").inTable("vendor_bills").onDelete("RESTRICT");
        table.index(["vendor_bill_id"], "idx_allocations_vendor_bill_id");
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    // 1. Revert payment_allocations
    await knex.schema.alterTable("payment_allocations", function (table) {
        table.dropIndex(["vendor_bill_id"], "idx_allocations_vendor_bill_id");
        table.dropColumn("vendor_bill_id");
        table.integer("invoice_id").unsigned().notNullable().alter();
    });

    // 2. Drop vendor_bills table
    await knex.schema.dropTableIfExists("vendor_bills");
};
