const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    if (!(await knex.schema.hasTable('firm_branches'))) {
        await knex.schema.createTable('firm_branches', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.string('branch_name', 150).notNullable();
            table.string('branch_code', 50).notNullable();
            table.string('gstin', 20).nullable();
            table.string('phone', 30).nullable();
            table.string('email', 150).nullable();
            table.text('address_line1').nullable();
            table.text('address_line2').nullable();
            table.integer('city_id').unsigned().nullable().references('id').inTable('city').onDelete('SET NULL');
            table.integer('state_id').unsigned().nullable().references('id').inTable('state').onDelete('SET NULL');
            table.string('pincode', 10).nullable();
            table.boolean('is_head_office').notNullable().defaultTo(false);
            table.boolean('is_default').notNullable().defaultTo(false);
            addDefaultColumns(table, knex);

            table.unique(['firm_id', 'branch_code'], { indexName: 'uq_firm_branches_firm_code' });
            table.index(['firm_id', 'is_active'], 'idx_firm_branches_firm_active');
        });
    }

    // Data Backfill: Ensure all existing firms have a default Head Office branch
    const existingFirms = await knex('firms').select('id', 'firm_name', 'gstin');
    for (const firm of existingFirms) {
        const existingBranch = await knex('firm_branches').where({ firm_id: firm.id }).first();
        if (!existingBranch) {
            await knex('firm_branches').insert({
                firm_id: firm.id,
                branch_name: 'Head Office',
                branch_code: 'HO',
                gstin: firm.gstin || null,
                is_head_office: true,
                is_default: true,
                is_active: true
            });
        }
    }
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('firm_branches');
};
