const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. employee_attendance table
    if (!(await knex.schema.hasTable('employee_attendance'))) {
        await knex.schema.createTable('employee_attendance', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('employee_id').unsigned().notNullable().references('id').inTable('employees').onDelete('CASCADE');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.integer('branch_id').unsigned().nullable().references('id').inTable('firm_branches').onDelete('SET NULL');
            table.integer('shift_id').unsigned().nullable().references('id').inTable('shifts').onDelete('SET NULL');

            table.date('attendance_date').notNullable();
            table.string('status', 20).notNullable().defaultTo('PRESENT');
            // Statuses: PRESENT | ABSENT | HALF_DAY | LATE | LEAVE | HOLIDAY | WEEKLY_OFF

            table.time('check_in').nullable();
            table.time('check_out').nullable();
            table.decimal('total_hours', 6, 2).defaultTo(0);
            table.decimal('overtime_hours', 6, 2).defaultTo(0);
            table.string('overtime_type', 20).defaultTo('NORMAL'); // NORMAL | HOLIDAY | WEEKEND

            table.text('remarks').nullable();
            table.integer('marked_by').unsigned().nullable().references('id').inTable('users').onDelete('SET NULL');

            addDefaultColumns(table, knex);

            table.unique(['employee_id', 'attendance_date'], { indexName: 'uq_attendance_emp_date' });
            table.index(['firm_id', 'attendance_date'], 'idx_attendance_firm_date');
            table.index(['employee_id', 'attendance_date'], 'idx_attendance_emp_date');
            table.index(['firm_id', 'status'], 'idx_attendance_firm_status');
        });
    }

    // 2. employee_leaves table
    if (!(await knex.schema.hasTable('employee_leaves'))) {
        await knex.schema.createTable('employee_leaves', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('employee_id').unsigned().notNullable().references('id').inTable('employees').onDelete('CASCADE');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');

            table.string('leave_type', 30).notNullable(); // CASUAL | SICK | EARNED | UNPAID | COMP_OFF
            table.date('from_date').notNullable();
            table.date('to_date').notNullable();
            table.decimal('total_days', 5, 1).notNullable(); // supports 0.5 for half day
            table.string('half_day_on', 10).nullable(); // FROM | TO

            table.text('reason').nullable();
            table.string('status', 20).notNullable().defaultTo('PENDING'); // PENDING | APPROVED | REJECTED | CANCELLED
            table.integer('approved_by').unsigned().nullable().references('id').inTable('users').onDelete('SET NULL');
            table.timestamp('approved_at').nullable();
            table.text('rejection_reason').nullable();

            addDefaultColumns(table, knex);

            table.index(['firm_id', 'status'], 'idx_leaves_firm_status');
            table.index(['employee_id', 'from_date'], 'idx_leaves_emp_from_date');
            table.index(['firm_id', 'from_date', 'to_date'], 'idx_leaves_firm_dates');
        });
    }
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('employee_leaves');
    await knex.schema.dropTableIfExists('employee_attendance');
};
