const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. Create party_branches table
    if (!(await knex.schema.hasTable('party_branches'))) {
        await knex.schema.createTable('party_branches', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.integer('party_id').unsigned().notNullable().references('id').inTable('parties').onDelete('CASCADE');
            table.string('branch_name', 100).notNullable();
            table.string('branch_code', 50).nullable();
            table.string('gstin', 20).nullable();
            table.integer('state_id').unsigned().notNullable().references('id').inTable('state');
            table.boolean('is_head_office').notNullable().defaultTo(false);
            table.boolean('is_default').notNullable().defaultTo(false);
            table.string('email', 150).nullable();
            table.string('mobile', 20).nullable();
            table.text('remarks').nullable();
            addDefaultColumns(table, knex);

            table.index(['party_id', 'firm_id'], 'idx_party_branches_party_firm');
        });
    }

    // 2. Add branch_id to party_addresses
    if (await knex.schema.hasTable('party_addresses')) {
        const hasBranchCol = await knex.schema.hasColumn('party_addresses', 'branch_id');
        if (!hasBranchCol) {
            await knex.schema.alterTable('party_addresses', function (table) {
                table.integer('branch_id').unsigned().nullable().index('idx_party_addresses_branch')
                    .references('id').inTable('party_branches').onDelete('CASCADE');
            });
        }
    }

    // 3. Add branch_id to party_contacts
    if (await knex.schema.hasTable('party_contacts')) {
        const hasBranchCol = await knex.schema.hasColumn('party_contacts', 'branch_id');
        if (!hasBranchCol) {
            await knex.schema.alterTable('party_contacts', function (table) {
                table.integer('branch_id').unsigned().nullable().index('idx_party_contacts_branch')
                    .references('id').inTable('party_branches').onDelete('SET NULL');
            });
        }
    }

    // 4. Add party_id and branch_id to invoices
    if (await knex.schema.hasTable('invoices')) {
        const hasPartyCol = await knex.schema.hasColumn('invoices', 'party_id');
        const hasBranchCol = await knex.schema.hasColumn('invoices', 'branch_id');

        await knex.schema.alterTable('invoices', function (table) {
            if (!hasPartyCol) {
                table.integer('party_id').unsigned().nullable().index('idx_invoices_party')
                    .references('id').inTable('parties').onDelete('SET NULL');
            }
            if (!hasBranchCol) {
                table.integer('branch_id').unsigned().nullable().index('idx_invoices_branch')
                    .references('id').inTable('party_branches').onDelete('SET NULL');
            }
        });
    }

    // 5. Add branch_name and gstin to invoice_contacts
    if (await knex.schema.hasTable('invoice_contacts')) {
        const hasBranchNameCol = await knex.schema.hasColumn('invoice_contacts', 'branch_name');
        const hasGstinCol = await knex.schema.hasColumn('invoice_contacts', 'gstin');

        await knex.schema.alterTable('invoice_contacts', function (table) {
            if (!hasBranchNameCol) {
                table.string('branch_name', 100).nullable();
            }
            if (!hasGstinCol) {
                table.string('gstin', 20).nullable();
            }
        });
    }

    // 6. Data Backfill: Ensure existing parties have a default "Head Office" branch
    const existingParties = await knex('parties').select('id', 'firm_id', 'party_code', 'gstin', 'email', 'mobile', 'is_active');
    
    // Get default state (Maharashtra or first state) as fallback
    const defaultState = await knex('state').whereILike('name', '%MAHARASHTRA%').first() || await knex('state').first();
    const fallbackStateId = defaultState?.id || 1;
    const firstUser = await knex('users').select('id').first();
    const defaultUserId = firstUser?.id || null;

    for (const party of existingParties) {
        // Check if party already has any branch
        const existingBranch = await knex('party_branches').where({ party_id: party.id }).first();
        let branchId;

        if (!existingBranch) {
            // Find address state if available
            const partyAddr = await knex('party_addresses').where({ party_id: party.id }).orderBy('id', 'asc').first();
            const stateId = partyAddr?.state_id || fallbackStateId;

            const [createdBranch] = await knex('party_branches').insert({
                firm_id: party.firm_id,
                party_id: party.id,
                branch_name: 'Head Office',
                branch_code: party.party_code ? `${party.party_code}-HO` : null,
                gstin: party.gstin || null,
                state_id: stateId,
                is_head_office: true,
                is_default: true,
                email: party.email || null,
                mobile: party.mobile || null,
                created_by: defaultUserId,
                updated_by: defaultUserId,
                is_active: party.is_active !== undefined ? party.is_active : true
            }).returning('id');

            branchId = createdBranch?.id || createdBranch;
        } else {
            branchId = existingBranch.id;
        }

        // Link any unlinked addresses for this party to the branch
        if (branchId) {
            await knex('party_addresses')
                .where({ party_id: party.id })
                .whereNull('branch_id')
                .update({ branch_id: branchId });

            await knex('party_contacts')
                .where({ party_id: party.id })
                .whereNull('branch_id')
                .update({ branch_id: branchId });
        }
    }
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    if (await knex.schema.hasTable('invoice_contacts')) {
        await knex.schema.alterTable('invoice_contacts', function (table) {
            table.dropColumn('branch_name');
            table.dropColumn('gstin');
        });
    }

    if (await knex.schema.hasTable('invoices')) {
        await knex.schema.alterTable('invoices', function (table) {
            table.dropColumn('branch_id');
            table.dropColumn('party_id');
        });
    }

    if (await knex.schema.hasTable('party_contacts')) {
        await knex.schema.alterTable('party_contacts', function (table) {
            table.dropColumn('branch_id');
        });
    }

    if (await knex.schema.hasTable('party_addresses')) {
        await knex.schema.alterTable('party_addresses', function (table) {
            table.dropColumn('branch_id');
        });
    }

    await knex.schema.dropTableIfExists('party_branches');
};
