const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable("party_bank_accounts", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("party_id").unsigned().notNullable().references("id").inTable("parties").onDelete("CASCADE");
        table.string("bank_name", 100).notNullable();
        table.string("account_number", 50).notNullable();
        table.string("ifsc_code", 20);
        table.string("branch_name", 100);
        table.string("account_holder_name", 200).notNullable();
        table.string("upi_id", 100);
        table.boolean("is_primary").notNullable().defaultTo(false);
        addDefaultColumns(table, knex);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists("party_bank_accounts");
};
