const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. Create payments ledger table
    await knex.schema.createTable("payments", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("firm_id").unsigned().notNullable().references("id").inTable("firms").onDelete("CASCADE");
        
        table.string("payment_no", 50).notNullable(); // e.g. 'REC-0001', 'PAY-0001'
        table.string("payment_type", 20).notNullable().defaultTo("INWARD"); // 'INWARD' (Receipt) | 'OUTWARD' (Payment)
        table.date("payment_date").notNullable();
        table.integer("party_id").unsigned().notNullable().references("id").inTable("parties").onDelete("RESTRICT");
        
        // Monetary totals
        table.decimal("total_amount", 12, 2).notNullable().defaultTo(0.00);      // Total cash/bank received
        table.decimal("allocated_amount", 12, 2).notNullable().defaultTo(0.00);  // Amount knocked off invoices
        table.decimal("unallocated_amount", 12, 2).notNullable().defaultTo(0.00); // Remaining advance balance
        
        // Payment mode & banking details
        table.integer("payment_mode_id").unsigned().notNullable().references("id").inTable("payment_modes").onDelete("RESTRICT");
        table.string("reference_no", 100).nullable();  // UTR / Cheque No / Txn ID
        table.date("reference_date").nullable();        // Cheque date / Clearance date
        table.string("bank_name", 150).nullable();     // Bank name
        
        // Status & Notes
        table.string("status", 20).notNullable().defaultTo("COMPLETED"); // 'COMPLETED', 'CANCELLED'
        table.text("notes").nullable();
        
        // Default audit columns (created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, is_active)
        addDefaultColumns(table, knex);
        
        // Constraints and indexes
        table.unique(["firm_id", "payment_no"], "unq_payments_firm_payment_no");
        table.index(["firm_id", "payment_type", "is_active"], "idx_payments_firm_type");
        table.index(["firm_id", "party_id", "is_active"], "idx_payments_firm_party");
        table.index(["firm_id", "payment_date"], "idx_payments_firm_date");
    });

    // 2. Create payment allocations junction table
    await knex.schema.createTable("payment_allocations", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("payment_id").unsigned().notNullable().references("id").inTable("payments").onDelete("CASCADE");
        table.integer("invoice_id").unsigned().notNullable().references("id").inTable("invoices").onDelete("RESTRICT");
        
        table.decimal("allocated_amount", 12, 2).notNullable().defaultTo(0.00);      // Cash/Bank applied
        table.decimal("tds_amount", 12, 2).notNullable().defaultTo(0.00);            // Tax deducted at source
        table.decimal("write_off_amount", 12, 2).notNullable().defaultTo(0.00);      // Settlement discount / write-off
        table.string("write_off_reason", 255).nullable();                            // Reason for write-off
        table.decimal("total_settled_amount", 12, 2).notNullable().defaultTo(0.00);  // (allocated + tds + write_off)
        
        addDefaultColumns(table, knex);
        
        table.index(["payment_id"], "idx_allocations_payment_id");
        table.index(["invoice_id"], "idx_allocations_invoice_id");
    });

    // 3. Add paid_amount and balance_amount to invoices table
    await knex.schema.alterTable("invoices", function (table) {
        table.decimal("paid_amount", 12, 2).notNullable().defaultTo(0.00);
        table.decimal("balance_amount", 12, 2).notNullable().defaultTo(0.00);
        table.index(["firm_id", "payment_status_id"], "idx_invoices_payment_status");
    });

    // 4. Backfill existing invoices safely
    const paidStatus = await knex('payment_statuses').where({ code: 'PAID' }).first();
    const paidStatusId = paidStatus ? paidStatus.id : 8;

    await knex('invoices')
        .where('payment_status_id', '!=', paidStatusId)
        .update({
            balance_amount: knex.raw('total'),
            paid_amount: 0.00
        });

    await knex('invoices')
        .where('payment_status_id', '=', paidStatusId)
        .update({
            paid_amount: knex.raw('total'),
            balance_amount: 0.00
        });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    // 1. Revert invoices columns
    await knex.schema.alterTable("invoices", function (table) {
        table.dropIndex(["firm_id", "payment_status_id"], "idx_invoices_payment_status");
        table.dropColumn("paid_amount");
        table.dropColumn("balance_amount");
    });

    // 2. Drop payment allocations
    await knex.schema.dropTableIfExists("payment_allocations");

    // 3. Drop payments ledger
    await knex.schema.dropTableIfExists("payments");
};
