const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable("parties", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("firm_id").unsigned().notNullable().references("id").inTable("firms").onDelete("CASCADE");
        table.string("party_code", 50).unique().notNullable();
        table.string("legal_name", 200).notNullable();
        table.string("display_name", 200);
        table.string("mobile", 15);
        table.string("email", 150);
        table.boolean("gst_registered").defaultTo(false);
        table.string("gstin", 20);
        table.string('cin_number');
        table.string('tan_number');
        table.string("pan_number", 20);
        table.string("website", 200);
        table.text("remarks");
        table.string("status", 20).defaultTo("active");
        addDefaultColumns(table, knex);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists("parties");
};
