const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
    return knex.schema.createTable("party_role_mapping", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("party_id").unsigned().notNullable().references("id").inTable("parties").onDelete("CASCADE");
        table.integer("party_role_id").unsigned().notNullable().references("id").inTable("party_roles").onDelete("RESTRICT");
        addDefaultColumns(table, knex);

        table.unique(["party_id", "party_role_id"]);
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
    return knex.schema.dropTableIfExists("party_role_mapping");
};
