const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. firm_payroll_settings table
    if (!(await knex.schema.hasTable('firm_payroll_settings'))) {
        await knex.schema.createTable('firm_payroll_settings', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('firm_id').unsigned().notNullable().unique().references('id').inTable('firms').onDelete('CASCADE');

            // Working days config
            table.integer('working_days_per_month').defaultTo(26);
            table.string('weekly_off_day', 20).defaultTo('SUNDAY'); // SUNDAY | SATURDAY | NONE

            // Overtime config (firm-specific)
            table.string('ot_rate_type', 20).defaultTo('FIXED'); // FIXED | MULTIPLIER
            table.decimal('ot_hourly_rate', 10, 2).defaultTo(0);
            table.decimal('ot_multiplier_normal', 4, 2).defaultTo(1.5);
            table.decimal('ot_multiplier_holiday', 4, 2).defaultTo(2.0);
            table.decimal('ot_multiplier_weekend', 4, 2).defaultTo(2.0);

            // Statutory (only applied to PERMANENT employees)
            table.boolean('pf_enabled').defaultTo(false);
            table.decimal('pf_employer_percent', 5, 2).defaultTo(12.00);
            table.decimal('pf_employee_percent', 5, 2).defaultTo(12.00);
            table.decimal('pf_wage_ceiling', 12, 2).defaultTo(15000.00);

            table.boolean('esi_enabled').defaultTo(false);
            table.decimal('esi_employer_percent', 5, 2).defaultTo(3.25);
            table.decimal('esi_employee_percent', 5, 2).defaultTo(0.75);
            table.decimal('esi_wage_ceiling', 12, 2).defaultTo(21000.00);

            table.boolean('pt_enabled').defaultTo(false);
            table.decimal('pt_monthly_amount', 10, 2).defaultTo(200.00);

            addDefaultColumns(table, knex);
        });
    }

    // 2. employee_salary_slips table
    if (!(await knex.schema.hasTable('employee_salary_slips'))) {
        await knex.schema.createTable('employee_salary_slips', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('employee_id').unsigned().notNullable().references('id').inTable('employees').onDelete('CASCADE');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');

            // Period
            table.integer('month').notNullable(); // 1-12
            table.integer('year').notNullable();

            // Attendance summary
            table.decimal('total_working_days', 5, 1).defaultTo(0);
            table.decimal('present_days', 5, 1).defaultTo(0);
            table.decimal('absent_days', 5, 1).defaultTo(0);
            table.decimal('half_days', 5, 1).defaultTo(0);
            table.decimal('paid_leave_days', 5, 1).defaultTo(0);
            table.decimal('overtime_hours', 6, 2).defaultTo(0);

            // Salary amounts
            table.decimal('gross_earnings', 14, 2).defaultTo(0);
            table.decimal('total_deductions', 14, 2).defaultTo(0);
            table.decimal('overtime_pay', 12, 2).defaultTo(0);
            table.decimal('net_salary', 14, 2).defaultTo(0);

            // Status: DRAFT | GENERATED | APPROVED | PAID
            table.string('status', 20).defaultTo('DRAFT');
            table.integer('generated_by').unsigned().nullable().references('id').inTable('users').onDelete('SET NULL');
            table.integer('approved_by').unsigned().nullable().references('id').inTable('users').onDelete('SET NULL');
            table.timestamp('approved_at').nullable();

            // Payment
            table.date('payment_date').nullable();
            table.string('payment_mode', 30).nullable(); // BANK_TRANSFER | CASH | UPI | CHEQUE
            table.string('payment_reference', 150).nullable();
            table.text('remarks').nullable();

            addDefaultColumns(table, knex);

            table.unique(['employee_id', 'month', 'year'], { indexName: 'uq_salary_slips_emp_month_year' });
            table.index(['firm_id', 'month', 'year'], 'idx_salary_slips_firm_period');
            table.index(['firm_id', 'status'], 'idx_salary_slips_firm_status');
        });
    }

    // 3. salary_slip_details table
    if (!(await knex.schema.hasTable('salary_slip_details'))) {
        await knex.schema.createTable('salary_slip_details', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('salary_slip_id').unsigned().notNullable().references('id').inTable('employee_salary_slips').onDelete('CASCADE');
            table.string('component_name', 100).notNullable();
            table.string('component_type', 20).notNullable(); // EARNING | DEDUCTION
            table.decimal('amount', 12, 2).notNullable().defaultTo(0);
            table.integer('sort_order').defaultTo(0);
            addDefaultColumns(table, knex);

            table.index(['salary_slip_id', 'component_type'], 'idx_slip_details_type');
        });
    }
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists('salary_slip_details');
    await knex.schema.dropTableIfExists('employee_salary_slips');
    await knex.schema.dropTableIfExists('firm_payroll_settings');
};
