const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * Migration for Employee Salary Advances and Repayments
 *
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    // 1. employee_advances table
    if (!(await knex.schema.hasTable('employee_advances'))) {
        await knex.schema.createTable('employee_advances', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.integer('employee_id').unsigned().notNullable().references('id').inTable('employees').onDelete('CASCADE');

            table.date('advance_date').notNullable();
            table.decimal('total_amount', 12, 2).notNullable();
            table.string('recovery_type', 20).notNullable().defaultTo('FULL'); // FULL | EMI | CUSTOM
            table.decimal('monthly_deduction', 12, 2).notNullable().defaultTo(0);
            table.decimal('recovered_amount', 12, 2).notNullable().defaultTo(0);
            table.decimal('remaining_balance', 12, 2).notNullable().defaultTo(0);
            table.boolean('is_paused').defaultTo(false);
            table.string('status', 20).notNullable().defaultTo('ACTIVE'); // ACTIVE | PAUSED | CLOSED | CANCELLED

            // Payment disbursement details
            table.string('payment_mode', 30).defaultTo('CASH'); // CASH | BANK_TRANSFER | UPI | CHEQUE
            table.string('payment_reference', 150).nullable();
            table.integer('disbursed_by').unsigned().nullable().references('id').inTable('users').onDelete('SET NULL');
            table.text('remarks').nullable();

            addDefaultColumns(table, knex);

            table.index(['firm_id', 'employee_id'], 'idx_advances_firm_emp');
            table.index(['firm_id', 'status'], 'idx_advances_firm_status');
        });
    }

    // 2. employee_advance_repayments table (Repayment Audit & History)
    if (!(await knex.schema.hasTable('employee_advance_repayments'))) {
        await knex.schema.createTable('employee_advance_repayments', function (table) {
            table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
            table.integer('advance_id').unsigned().notNullable().references('id').inTable('employee_advances').onDelete('CASCADE');
            table.integer('firm_id').unsigned().notNullable().references('id').inTable('firms').onDelete('CASCADE');
            table.integer('employee_id').unsigned().notNullable().references('id').inTable('employees').onDelete('CASCADE');
            table.integer('salary_slip_id').unsigned().nullable().references('id').inTable('employee_salary_slips').onDelete('SET NULL');

            table.date('repayment_date').notNullable();
            table.decimal('amount_deducted', 12, 2).notNullable();
            table.string('repayment_type', 30).notNullable().defaultTo('PAYROLL_DEDUCTION'); // PAYROLL_DEDUCTION | DIRECT_CASH | DIRECT_BANK
            table.decimal('balance_after', 12, 2).notNullable().defaultTo(0);
            table.integer('recorded_by').unsigned().nullable().references('id').inTable('users').onDelete('SET NULL');
            table.text('remarks').nullable();

            addDefaultColumns(table, knex);

            table.index(['advance_id'], 'idx_repay_advance');
            table.index(['salary_slip_id'], 'idx_repay_slip');
            table.index(['firm_id', 'employee_id'], 'idx_repay_firm_emp');
        });
    }

    // 3. Add advance_deduction column to employee_salary_slips if missing
    if (await knex.schema.hasTable('employee_salary_slips')) {
        const hasColumn = await knex.schema.hasColumn('employee_salary_slips', 'advance_deduction');
        if (!hasColumn) {
            await knex.schema.table('employee_salary_slips', function (table) {
                table.decimal('advance_deduction', 14, 2).defaultTo(0);
            });
        }
    }
};

/**
 * Rollback migration
 *
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    if (await knex.schema.hasTable('employee_salary_slips')) {
        const hasColumn = await knex.schema.hasColumn('employee_salary_slips', 'advance_deduction');
        if (hasColumn) {
            await knex.schema.table('employee_salary_slips', function (table) {
                table.dropColumn('advance_deduction');
            });
        }
    }
    await knex.schema.dropTableIfExists('employee_advance_repayments');
    await knex.schema.dropTableIfExists('employee_advances');
};
