const { addDefaultColumns } = require("../src/api/v1/helpers/patchKnex");

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
    await knex.schema.createTable("products", function (table) {
        table.specificType('id', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table.integer("firm_id").unsigned().notNullable().references("id").inTable("firms").onDelete("CASCADE");

        // Basic Identification
        table.string("item_code", 50).nullable(); // SKU / Part Code (e.g. 'KS-FLG-100')
        table.string("name", 255).notNullable(); // Part / Service Name
        table.string("item_type", 30).notNullable().defaultTo("FINISHED_GOODS"); // 'RAW_MATERIAL', 'FINISHED_GOODS', 'SERVICE', 'CONSUMABLE'

        // Tax & Accounting
        table.string("hsn_sac_code", 20).nullable();
        table.integer("gst_slab_id").unsigned().nullable().references("id").inTable("gst_slabs").onDelete("SET NULL");
        table.integer("item_unit_id").unsigned().nullable().references("id").inTable("item_units").onDelete("SET NULL");

        // Pricing
        table.decimal("selling_price", 12, 2).defaultTo(0.00); // Default for Invoices & Quotations
        table.decimal("purchase_price", 12, 2).defaultTo(0.00); // Default for Purchase Orders

        // Engineering Specifications
        table.string("drawing_number", 150).nullable(); // e.g. 'DWG-KS-2026-084 Rev 2'
        table.string("material_grade", 100).nullable(); // e.g. 'SS 304', 'EN8', 'MS IS 2062'
        table.string("dimensions", 200).nullable(); // e.g. 'OD 120mm x ID 45mm x Thk 25mm'
        table.decimal("unit_weight_kg", 10, 3).nullable(); // Weight per unit in Kg

        // Description & Notes
        table.text("description").nullable();
        table.text("notes").nullable();

        // Status & Auditing
        table.string("status", 20).notNullable().defaultTo("ACTIVE"); // 'ACTIVE', 'INACTIVE'
        addDefaultColumns(table, knex);

        // Constraints & Indexes
        table.unique(["item_code", "firm_id"], "unq_products_item_code_firm");
        table.index(["firm_id", "is_active"], "idx_products_firm_active");
        table.index(["firm_id", "item_type", "is_active"], "idx_products_firm_type");
        table.index(["firm_id", "name"], "idx_products_search_name");
        table.index(["firm_id", "drawing_number"], "idx_products_drawing_no");
        table.index(["firm_id", "material_grade"], "idx_products_material_grade");
    });

    // Add CHECK constraint for item_type
    await knex.raw(`
        ALTER TABLE products 
        ADD CONSTRAINT chk_product_item_type 
        CHECK (item_type IN ('RAW_MATERIAL', 'FINISHED_GOODS', 'SERVICE', 'CONSUMABLE'))
    `);
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
    await knex.schema.dropTableIfExists("products");
};
