exports.seed = async function (knex) {
  // Clear existing data
  await knex("city").del();

  // Insert cities
  await knex("city").insert([
    // ANDAMAN & NICOBAR (32)
    { id: 1, name: "North and Middle Andaman", state_id: 32, created_by: 1, updated_by: 1 },
    { id: 2, name: "South Andaman", state_id: 32, created_by: 1, updated_by: 1 },
    { id: 3, name: "Nicobar", state_id: 32, created_by: 1, updated_by: 1 },

    // ANDHRA PRADESH (1)
    { id: 4, name: "Adilabad", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 5, name: "Anantapur", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 6, name: "Chittoor", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 7, name: "East Godavari", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 8, name: "Guntur", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 9, name: "Hyderabad", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 10, name: "Kadapa", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 11, name: "Karimnagar", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 12, name: "Khammam", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 13, name: "Krishna", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 14, name: "Kurnool", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 15, name: "Mahbubnagar", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 16, name: "Medak", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 17, name: "Nalgonda", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 18, name: "Nellore", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 19, name: "Nizamabad", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 20, name: "Prakasam", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 21, name: "Rangareddi", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 22, name: "Srikakulam", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 23, name: "Vishakhapatnam", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 24, name: "Vizianagaram", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 25, name: "Warangal", state_id: 1, created_by: 1, updated_by: 1 },
    { id: 26, name: "West Godavari", state_id: 1, created_by: 1, updated_by: 1 },

    // ARUNACHAL PRADESH (3)
    { id: 27, name: "Anjaw", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 28, name: "Changlang", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 29, name: "East Kameng", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 30, name: "Lohit", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 31, name: "Lower Subansiri", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 32, name: "Papum Pare", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 33, name: "Tirap", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 34, name: "Dibang Valley", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 35, name: "Upper Subansiri", state_id: 3, created_by: 1, updated_by: 1 },
    { id: 36, name: "West Kameng", state_id: 3, created_by: 1, updated_by: 1 },

    // ASSAM (2)
    { id: 37, name: "Barpeta", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 38, name: "Bongaigaon", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 39, name: "Cachar", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 40, name: "Darrang", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 41, name: "Dhemaji", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 42, name: "Dhubri", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 43, name: "Dibrugarh", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 44, name: "Goalpara", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 45, name: "Golaghat", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 46, name: "Hailakandi", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 47, name: "Jorhat", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 48, name: "Karbi Anglong", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 49, name: "Karimganj", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 50, name: "Kokrajhar", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 51, name: "Lakhimpur", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 52, name: "Marigaon", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 53, name: "Nagaon", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 54, name: "Nalbari", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 55, name: "North Cachar Hills", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 56, name: "Sibsagar", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 57, name: "Sonitpur", state_id: 2, created_by: 1, updated_by: 1 },
    { id: 58, name: "Tinsukia", state_id: 2, created_by: 1, updated_by: 1 },

    // BIHAR (4)
    { id: 59, name: "Araria", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 60, name: "Aurangabad", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 61, name: "Banka", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 62, name: "Begusarai", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 63, name: "Bhagalpur", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 64, name: "Bhojpur", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 65, name: "Buxar", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 66, name: "Darbhanga", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 67, name: "Purba Champaran", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 68, name: "Gaya", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 69, name: "Gopalganj", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 70, name: "Jamui", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 71, name: "Jehanabad", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 72, name: "Khagaria", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 73, name: "Kishanganj", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 74, name: "Kaimur", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 75, name: "Katihar", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 76, name: "Lakhisarai", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 77, name: "Madhubani", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 78, name: "Munger", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 79, name: "Madhepura", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 80, name: "Muzaffarpur", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 81, name: "Nalanda", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 82, name: "Nawada", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 83, name: "Patna", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 84, name: "Purnia", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 85, name: "Rohtas", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 86, name: "Saharsa", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 87, name: "Samastipur", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 88, name: "Sheohar", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 89, name: "Sheikhpura", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 90, name: "Saran", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 91, name: "Sitamarhi", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 92, name: "Supaul", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 93, name: "Siwan", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 94, name: "Vaishali", state_id: 4, created_by: 1, updated_by: 1 },
    { id: 95, name: "Pashchim Champaran", state_id: 4, created_by: 1, updated_by: 1 },

    // CHHATTISGARH (36)
    { id: 96, name: "Bastar", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 97, name: "Bilaspur", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 98, name: "Dantewada", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 99, name: "Dhamtari", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 100, name: "Durg", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 101, name: "Jashpur", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 102, name: "Janjgir-Champa", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 103, name: "Korba", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 104, name: "Koriya", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 105, name: "Kanker", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 106, name: "Kawardha", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 107, name: "Mahasamund", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 108, name: "Raigarh", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 109, name: "Rajnandgaon", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 110, name: "Raipur", state_id: 35, created_by: 1, updated_by: 1 },
    { id: 111, name: "Surguja", state_id: 35, created_by: 1, updated_by: 1 },

    // DAMAN & DIU (29)
    { id: 112, name: "Diu", state_id: 29, created_by: 1, updated_by: 1 },
    { id: 113, name: "Daman", state_id: 29, created_by: 1, updated_by: 1 },

    // DELHI (25)
    { id: 114, name: "Central Delhi", state_id: 25, created_by: 1, updated_by: 1 },
    { id: 115, name: "East Delhi", state_id: 25, created_by: 1, updated_by: 1 },
    { id: 116, name: "New Delhi", state_id: 25, created_by: 1, updated_by: 1 },
    { id: 117, name: "North Delhi", state_id: 25, created_by: 1, updated_by: 1 },
    { id: 118, name: "North East Delhi", state_id: 25, created_by: 1, updated_by: 1 },
    { id: 119, name: "North West Delhi", state_id: 25, created_by: 1, updated_by: 1 },
    { id: 120, name: "South Delhi", state_id: 25, created_by: 1, updated_by: 1 },
    { id: 121, name: "South West Delhi", state_id: 25, created_by: 1, updated_by: 1 },
    { id: 122, name: "West Delhi", state_id: 25, created_by: 1, updated_by: 1 },

    // GOA (26)
    { id: 123, name: "North Goa", state_id: 26, created_by: 1, updated_by: 1 },
    { id: 124, name: "South Goa", state_id: 26, created_by: 1, updated_by: 1 },

    // GUJARAT (5)
    { id: 125, name: "Ahmedabad", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 126, name: "Amreli District", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 127, name: "Anand", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 128, name: "Banaskantha", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 129, name: "Bharuch", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 130, name: "Bhavnagar", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 131, name: "Dahod", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 132, name: "The Dangs", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 133, name: "Gandhinagar", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 134, name: "Jamnagar", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 135, name: "Junagadh", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 136, name: "Kutch", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 137, name: "Kheda", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 138, name: "Mehsana", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 139, name: "Narmada", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 140, name: "Navsari", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 141, name: "Patan", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 142, name: "Panchmahal", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 143, name: "Porbandar", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 144, name: "Rajkot", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 145, name: "Sabarkantha", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 146, name: "Surendranagar", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 147, name: "Surat", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 148, name: "Vadodara", state_id: 5, created_by: 1, updated_by: 1 },
    { id: 149, name: "Valsad", state_id: 5, created_by: 1, updated_by: 1 },

    // HARYANA (6)
    { id: 150, name: "Ambala", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 151, name: "Bhiwani", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 152, name: "Faridabad", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 153, name: "Fatehabad", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 154, name: "Gurgaon", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 155, name: "Hissar", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 156, name: "Jhajjar", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 157, name: "Jind", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 158, name: "Karnal", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 159, name: "Kaithal", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 160, name: "Kurukshetra", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 161, name: "Mahendragarh", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 162, name: "Mewat", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 163, name: "Panchkula", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 164, name: "Panipat", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 165, name: "Rewari", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 166, name: "Rohtak", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 167, name: "Sirsa", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 168, name: "Sonepat", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 169, name: "Yamuna Nagar", state_id: 6, created_by: 1, updated_by: 1 },
    { id: 170, name: "Palwal", state_id: 6, created_by: 1, updated_by: 1 },

    // HIMACHAL PRADESH (7)
    { id: 171, name: "Bilaspur", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 172, name: "Chamba", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 173, name: "Hamirpur", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 174, name: "Kangra", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 175, name: "Kinnaur", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 176, name: "Kulu", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 177, name: "Lahaul and Spiti", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 178, name: "Mandi", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 179, name: "Shimla", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 180, name: "Sirmaur", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 181, name: "Solan", state_id: 7, created_by: 1, updated_by: 1 },
    { id: 182, name: "Una", state_id: 7, created_by: 1, updated_by: 1 },

    // JAMMU & KASHMIR (8)
    { id: 183, name: "Anantnag", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 184, name: "Badgam", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 185, name: "Bandipore", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 186, name: "Baramula", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 187, name: "Doda", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 188, name: "Jammu", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 189, name: "Kargil", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 190, name: "Kathua", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 191, name: "Kupwara", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 192, name: "Leh", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 193, name: "Poonch", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 194, name: "Pulwama", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 195, name: "Rajauri", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 196, name: "Srinagar", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 197, name: "Samba", state_id: 8, created_by: 1, updated_by: 1 },
    { id: 198, name: "Udhampur", state_id: 8, created_by: 1, updated_by: 1 },

    // JHARKHAND (34)
    { id: 199, name: "Bokaro", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 200, name: "Chatra", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 201, name: "Deoghar", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 202, name: "Dhanbad", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 203, name: "Dumka", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 204, name: "Purba Singhbhum", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 205, name: "Garhwa", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 206, name: "Giridih", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 207, name: "Godda", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 208, name: "Gumla", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 209, name: "Hazaribagh", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 210, name: "Koderma", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 211, name: "Lohardaga", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 212, name: "Pakur", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 213, name: "Palamu", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 214, name: "Ranchi", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 215, name: "Sahibganj", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 216, name: "Seraikela and Kharsawan", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 217, name: "Pashchim Singhbhum", state_id: 34, created_by: 1, updated_by: 1 },
    { id: 218, name: "Ramgarh", state_id: 34, created_by: 1, updated_by: 1 },

    // KARNATAKA (9)
    { id: 219, name: "Bidar", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 220, name: "Belgaum", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 221, name: "Bijapur", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 222, name: "Bagalkot", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 223, name: "Bellary", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 224, name: "Bangalore Rural District", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 225, name: "Bangalore Urban District", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 226, name: "Chamarajnagar", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 227, name: "Chikmagalur", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 228, name: "Chitradurga", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 229, name: "Davanagere", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 230, name: "Dharwad", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 231, name: "Dakshina Kannada", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 232, name: "Gadag", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 233, name: "Gulbarga", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 234, name: "Hassan", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 235, name: "Haveri District", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 236, name: "Kodagu", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 237, name: "Kolar", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 238, name: "Koppal", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 239, name: "Mandya", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 240, name: "Mysore", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 241, name: "Raichur", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 242, name: "Shimoga", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 243, name: "Tumkur", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 244, name: "Udupi", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 245, name: "Uttara Kannada", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 246, name: "Ramanagara", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 247, name: "Chikballapur", state_id: 9, created_by: 1, updated_by: 1 },
    { id: 248, name: "Yadagiri", state_id: 9, created_by: 1, updated_by: 1 },

    // KERALA (10)
    { id: 249, name: "Alappuzha", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 250, name: "Ernakulam", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 251, name: "Idukki", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 252, name: "Kollam", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 253, name: "Kannur", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 254, name: "Kasaragod", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 255, name: "Kottayam", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 256, name: "Kozhikode", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 257, name: "Malappuram", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 258, name: "Palakkad", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 259, name: "Pathanamthitta", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 260, name: "Thrissur", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 261, name: "Thiruvananthapuram", state_id: 10, created_by: 1, updated_by: 1 },
    { id: 262, name: "Wayanad", state_id: 10, created_by: 1, updated_by: 1 },

    // MADHYA PRADESH (11)
    { id: 263, name: "Alirajpur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 264, name: "Anuppur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 265, name: "Ashok Nagar", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 266, name: "Balaghat", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 267, name: "Barwani", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 268, name: "Betul", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 269, name: "Bhind", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 270, name: "Bhopal", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 271, name: "Burhanpur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 272, name: "Chhatarpur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 273, name: "Chhindwara", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 274, name: "Damoh", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 275, name: "Datia", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 276, name: "Dewas", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 277, name: "Dhar", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 278, name: "Dindori", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 279, name: "Guna", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 280, name: "Gwalior", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 281, name: "Harda", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 282, name: "Hoshangabad", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 283, name: "Indore", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 284, name: "Jabalpur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 285, name: "Jhabua", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 286, name: "Katni", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 287, name: "Khandwa", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 288, name: "Khargone", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 289, name: "Mandla", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 290, name: "Mandsaur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 291, name: "Morena", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 292, name: "Narsinghpur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 293, name: "Neemuch", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 294, name: "Panna", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 295, name: "Rewa", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 296, name: "Rajgarh", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 297, name: "Ratlam", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 298, name: "Raisen", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 299, name: "Sagar", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 300, name: "Satna", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 301, name: "Sehore", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 302, name: "Seoni", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 303, name: "Shahdol", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 304, name: "Shajapur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 305, name: "Sheopur", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 306, name: "Shivpuri", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 307, name: "Sidhi", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 308, name: "Singrauli", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 309, name: "Tikamgarh", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 310, name: "Ujjain", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 311, name: "Umaria", state_id: 11, created_by: 1, updated_by: 1 },
    { id: 312, name: "Vidisha", state_id: 11, created_by: 1, updated_by: 1 },

    // MAHARASHTRA (12)
    { id: 313, name: "Ahmednagar", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 314, name: "Akola", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 315, name: "Amrawati", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 316, name: "Aurangabad", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 317, name: "Bhandara", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 318, name: "Beed", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 319, name: "Buldhana", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 320, name: "Chandrapur", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 321, name: "Dhule", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 322, name: "Gadchiroli", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 323, name: "Gondiya", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 324, name: "Hingoli", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 325, name: "Jalgaon", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 326, name: "Jalna", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 327, name: "Kolhapur", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 328, name: "Latur", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 329, name: "Mumbai City", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 330, name: "Mumbai suburban", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 331, name: "Nandurbar", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 332, name: "Nanded", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 333, name: "Nagpur", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 334, name: "Nashik", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 335, name: "Osmanabad", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 336, name: "Parbhani", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 337, name: "Pune", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 338, name: "Raigad", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 339, name: "Ratnagiri", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 340, name: "Sindhudurg", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 341, name: "Sangli", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 342, name: "Solapur", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 343, name: "Satara", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 344, name: "Thane", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 345, name: "Wardha", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 346, name: "Washim", state_id: 12, created_by: 1, updated_by: 1 },
    { id: 347, name: "Yavatmal", state_id: 12, created_by: 1, updated_by: 1 },

    // MANIPUR (13)
    { id: 348, name: "Bishnupur", state_id: 13, created_by: 1, updated_by: 1 },
    { id: 349, name: "Churachandpur", state_id: 13, created_by: 1, updated_by: 1 },
    { id: 350, name: "Chandel", state_id: 13, created_by: 1, updated_by: 1 },
    { id: 351, name: "Imphal East", state_id: 13, created_by: 1, updated_by: 1 },
    { id: 352, name: "Senapati", state_id: 13, created_by: 1, updated_by: 1 },
    { id: 353, name: "Tamenglong", state_id: 13, created_by: 1, updated_by: 1 },
    { id: 354, name: "Thoubal", state_id: 13, created_by: 1, updated_by: 1 },
    { id: 355, name: "Ukhrul", state_id: 13, created_by: 1, updated_by: 1 },
    { id: 356, name: "Imphal West", state_id: 13, created_by: 1, updated_by: 1 },

    // MEGHALAYA (14)
    { id: 357, name: "East Garo Hills", state_id: 14, created_by: 1, updated_by: 1 },
    { id: 358, name: "East Khasi Hills", state_id: 14, created_by: 1, updated_by: 1 },
    { id: 359, name: "Jaintia Hills", state_id: 14, created_by: 1, updated_by: 1 },
    { id: 360, name: "Ri-Bhoi", state_id: 14, created_by: 1, updated_by: 1 },
    { id: 361, name: "South Garo Hills", state_id: 14, created_by: 1, updated_by: 1 },
    { id: 362, name: "West Garo Hills", state_id: 14, created_by: 1, updated_by: 1 },
    { id: 363, name: "West Khasi Hills", state_id: 14, created_by: 1, updated_by: 1 },

    // MIZORAM (15)
    { id: 364, name: "Aizawl", state_id: 15, created_by: 1, updated_by: 1 },
    { id: 365, name: "Champhai", state_id: 15, created_by: 1, updated_by: 1 },
    { id: 366, name: "Kolasib", state_id: 15, created_by: 1, updated_by: 1 },
    { id: 367, name: "Lawngtlai", state_id: 15, created_by: 1, updated_by: 1 },
    { id: 368, name: "Lunglei", state_id: 15, created_by: 1, updated_by: 1 },
    { id: 369, name: "Mamit", state_id: 15, created_by: 1, updated_by: 1 },
    { id: 370, name: "Saiha", state_id: 15, created_by: 1, updated_by: 1 },
    { id: 371, name: "Serchhip", state_id: 15, created_by: 1, updated_by: 1 },

    // NAGALAND (16)
    { id: 372, name: "Dimapur", state_id: 16, created_by: 1, updated_by: 1 },
    { id: 373, name: "Kohima", state_id: 16, created_by: 1, updated_by: 1 },
    { id: 374, name: "Mokokchung", state_id: 16, created_by: 1, updated_by: 1 },
    { id: 375, name: "Mon", state_id: 16, created_by: 1, updated_by: 1 },
    { id: 376, name: "Phek", state_id: 16, created_by: 1, updated_by: 1 },
    { id: 377, name: "Tuensang", state_id: 16, created_by: 1, updated_by: 1 },
    { id: 378, name: "Wokha", state_id: 16, created_by: 1, updated_by: 1 },
    { id: 379, name: "Zunheboto", state_id: 16, created_by: 1, updated_by: 1 },

    // ODISHA (17)
    { id: 380, name: "Angul", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 381, name: "Boudh", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 382, name: "Bhadrak", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 383, name: "Bolangir", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 384, name: "Bargarh", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 385, name: "Baleswar", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 386, name: "Cuttack", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 387, name: "Debagarh", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 388, name: "Dhenkanal", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 389, name: "Ganjam", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 390, name: "Gajapati", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 391, name: "Jharsuguda", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 392, name: "Jajapur", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 393, name: "Jagatsinghpur", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 394, name: "Khordha", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 395, name: "Kendujhar", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 396, name: "Kalahandi", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 397, name: "Kandhamal", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 398, name: "Koraput", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 399, name: "Kendrapara", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 400, name: "Malkangiri", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 401, name: "Mayurbhanj", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 402, name: "Nabarangpur", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 403, name: "Nuapada", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 404, name: "Nayagarh", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 405, name: "Puri", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 406, name: "Rayagada", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 407, name: "Sambalpur", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 408, name: "Subarnapur", state_id: 17, created_by: 1, updated_by: 1 },
    { id: 409, name: "Sundargarh", state_id: 17, created_by: 1, updated_by: 1 },

    // PUDUCHERRY (27)
    { id: 410, name: "Karaikal", state_id: 27, created_by: 1, updated_by: 1 },
    { id: 411, name: "Mahe", state_id: 27, created_by: 1, updated_by: 1 },
    { id: 412, name: "Puducherry", state_id: 27, created_by: 1, updated_by: 1 },
    { id: 413, name: "Yanam", state_id: 27, created_by: 1, updated_by: 1 },

    // PUNJAB (18)
    { id: 414, name: "Amritsar", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 415, name: "Bathinda", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 416, name: "Firozpur", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 417, name: "Faridkot", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 418, name: "Fatehgarh Sahib", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 419, name: "Gurdaspur", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 420, name: "Hoshiarpur", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 421, name: "Jalandhar", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 422, name: "Kapurthala", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 423, name: "Ludhiana", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 424, name: "Mansa", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 425, name: "Moga", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 426, name: "Mukatsar", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 427, name: "Nawan Shehar", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 428, name: "Patiala", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 429, name: "Rupnagar", state_id: 18, created_by: 1, updated_by: 1 },
    { id: 430, name: "Sangrur", state_id: 18, created_by: 1, updated_by: 1 },

    // RAJASTHAN (19)
    { id: 431, name: "Ajmer", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 432, name: "Alwar", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 433, name: "Bikaner", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 434, name: "Barmer", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 435, name: "Banswara", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 436, name: "Bharatpur", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 437, name: "Baran", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 438, name: "Bundi", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 439, name: "Bhilwara", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 440, name: "Churu", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 441, name: "Chittorgarh", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 442, name: "Dausa", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 443, name: "Dholpur", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 444, name: "Dungapur", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 445, name: "Ganganagar", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 446, name: "Hanumangarh", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 447, name: "Juhnjhunun", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 448, name: "Jalore", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 449, name: "Jodhpur", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 450, name: "Jaipur", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 451, name: "Jaisalmer", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 452, name: "Jhalawar", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 453, name: "Karauli", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 454, name: "Kota", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 455, name: "Nagaur", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 456, name: "Pali", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 457, name: "Pratapgarh", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 458, name: "Rajsamand", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 459, name: "Sikar", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 460, name: "Sawai Madhopur", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 461, name: "Sirohi", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 462, name: "Tonk", state_id: 19, created_by: 1, updated_by: 1 },
    { id: 463, name: "Udaipur", state_id: 19, created_by: 1, updated_by: 1 },

    // SIKKIM (20)
    { id: 464, name: "East Sikkim", state_id: 20, created_by: 1, updated_by: 1 },
    { id: 465, name: "North Sikkim", state_id: 20, created_by: 1, updated_by: 1 },
    { id: 466, name: "South Sikkim", state_id: 20, created_by: 1, updated_by: 1 },
    { id: 467, name: "West Sikkim", state_id: 20, created_by: 1, updated_by: 1 },

    // TAMIL NADU (21)
    { id: 468, name: "Ariyalur", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 469, name: "Chennai", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 470, name: "Coimbatore", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 471, name: "Cuddalore", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 472, name: "Dharmapuri", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 473, name: "Dindigul", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 474, name: "Erode", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 475, name: "Kanchipuram", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 476, name: "Kanyakumari", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 477, name: "Karur", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 478, name: "Madurai", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 479, name: "Nagapattinam", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 480, name: "The Nilgiris", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 481, name: "Namakkal", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 482, name: "Perambalur", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 483, name: "Pudukkottai", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 484, name: "Ramanathapuram", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 485, name: "Salem", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 486, name: "Sivagangai", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 487, name: "Tiruppur", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 488, name: "Tiruchirappalli", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 489, name: "Theni", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 490, name: "Tirunelveli", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 491, name: "Thanjavur", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 492, name: "Thoothukudi", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 493, name: "Thiruvallur", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 494, name: "Thiruvarur", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 495, name: "Tiruvannamalai", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 496, name: "Vellore", state_id: 21, created_by: 1, updated_by: 1 },
    { id: 497, name: "Villupuram", state_id: 21, created_by: 1, updated_by: 1 },

    // TRIPURA (22)
    { id: 498, name: "Dhalai", state_id: 22, created_by: 1, updated_by: 1 },
    { id: 499, name: "North Tripura", state_id: 22, created_by: 1, updated_by: 1 },
    { id: 500, name: "South Tripura", state_id: 22, created_by: 1, updated_by: 1 },
    { id: 501, name: "West Tripura", state_id: 22, created_by: 1, updated_by: 1 },

    // UTTARAKHAND (33)
    { id: 502, name: "Almora", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 503, name: "Bageshwar", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 504, name: "Chamoli", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 505, name: "Champawat", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 506, name: "Dehradun", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 507, name: "Haridwar", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 508, name: "Nainital", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 509, name: "Pauri Garhwal", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 510, name: "Pithoragharh", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 511, name: "Rudraprayag", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 512, name: "Tehri Garhwal", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 513, name: "Udham Singh Nagar", state_id: 33, created_by: 1, updated_by: 1 },
    { id: 514, name: "Uttarkashi", state_id: 33, created_by: 1, updated_by: 1 },

    // UTTAR PRADESH (23)
    { id: 515, name: "Agra", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 516, name: "Allahabad", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 517, name: "Aligarh", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 518, name: "Ambedkar Nagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 519, name: "Auraiya", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 520, name: "Azamgarh", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 521, name: "Barabanki", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 522, name: "Badaun", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 523, name: "Bagpat", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 524, name: "Bahraich", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 525, name: "Bijnor", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 526, name: "Ballia", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 527, name: "Banda", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 528, name: "Balrampur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 529, name: "Bareilly", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 530, name: "Basti", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 531, name: "Bulandshahr", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 532, name: "Chandauli", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 533, name: "Chitrakoot", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 534, name: "Deoria", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 535, name: "Etah", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 536, name: "Kanshiram Nagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 537, name: "Etawah", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 538, name: "Firozabad", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 539, name: "Farrukhabad", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 540, name: "Fatehpur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 541, name: "Faizabad", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 542, name: "Gautam Buddha Nagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 543, name: "Gonda", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 544, name: "Ghazipur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 545, name: "Gorkakhpur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 546, name: "Ghaziabad", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 547, name: "Hamirpur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 548, name: "Hardoi", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 549, name: "Mahamaya Nagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 550, name: "Jhansi", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 551, name: "Jalaun", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 552, name: "Jyotiba Phule Nagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 553, name: "Jaunpur District", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 554, name: "Kanpur Dehat", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 555, name: "Kannauj", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 556, name: "Kanpur Nagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 557, name: "Kaushambi", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 558, name: "Kushinagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 559, name: "Lalitpur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 560, name: "Lakhimpur Kheri", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 561, name: "Lucknow", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 562, name: "Mau", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 563, name: "Meerut", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 564, name: "Maharajganj", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 565, name: "Mahoba", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 566, name: "Mirzapur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 567, name: "Moradabad", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 568, name: "Mainpuri", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 569, name: "Mathura", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 570, name: "Muzaffarnagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 571, name: "Pilibhit", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 572, name: "Pratapgarh", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 573, name: "Rampur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 574, name: "Rae Bareli", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 575, name: "Saharanpur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 576, name: "Sitapur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 577, name: "Shahjahanpur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 578, name: "Sant Kabir Nagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 579, name: "Siddharthnagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 580, name: "Sonbhadra", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 581, name: "Sant Ravidas Nagar", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 582, name: "Sultanpur", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 583, name: "Shravasti", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 584, name: "Unnao", state_id: 23, created_by: 1, updated_by: 1 },
    { id: 585, name: "Varanasi", state_id: 23, created_by: 1, updated_by: 1 },

    // WEST BENGAL (24)
    { id: 586, name: "Birbhum", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 587, name: "Bankura", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 588, name: "Bardhaman", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 589, name: "Darjeeling", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 590, name: "Dakshin Dinajpur", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 591, name: "Hooghly", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 592, name: "Howrah", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 593, name: "Jalpaiguri", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 594, name: "Cooch Behar", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 595, name: "Kolkata", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 596, name: "Malda", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 597, name: "Midnapore", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 598, name: "Murshidabad", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 599, name: "Nadia", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 600, name: "North 24 Parganas", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 601, name: "South 24 Parganas", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 602, name: "Purulia", state_id: 24, created_by: 1, updated_by: 1 },
    { id: 603, name: "Uttar Dinajpur", state_id: 24, created_by: 1, updated_by: 1 }
  ]);
};