[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, condition

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub.role == 'role:1' || (r.sub.role == p.sub && r.obj.name == p.obj && r.act == p.act && eval(p.condition))