const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTH_FAILED: 'AUTH_FAILED',
    NOT_FOUND: 'NOT_FOUND',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    FORBIDDEN: 'FORBIDDEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    CONFLICT: 'CONFLICT',
};

const SUCCESS_CODES = {
    OK: 'OK',
    CREATED: 'CREATED',
    UPDATED: 'UPDATED',
    DELETED: 'DELETED',
    LOGGED_IN: 'LOGGED_IN',
    LOGGED_OUT: 'LOGGED_OUT',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    DATA_FETCHED: 'DATA_FETCHED',
    EMAIL_SENT: 'EMAIL_SENT',
    OTP_VERIFIED: 'OTP_VERIFIED'
};

const STATUS_CODE_MAP = {
    200: SUCCESS_CODES.OK,
    201: SUCCESS_CODES.CREATED,
    204: SUCCESS_CODES.DELETED,
    400: ERROR_CODES.BAD_REQUEST,
    401: ERROR_CODES.UNAUTHORIZED,
    403: ERROR_CODES.FORBIDDEN,
    404: ERROR_CODES.NOT_FOUND,
    409: ERROR_CODES.CONFLICT,
    422: ERROR_CODES.VALIDATION_ERROR,
    500: ERROR_CODES.INTERNAL_ERROR
}

module.exports = {
    ERROR_CODES,
    SUCCESS_CODES,
    STATUS_CODE_MAP
};